### ISSUE TITLE
shallowUpgradeToDPCPPTensor is unsafe

### ISSUE THREAD

**Issue by ezyang** [intel/intel-extension-for-pytorch#144]
It does this:

```
    // [NOTE]: If the deleter of DPCPP::CPU is different form CPU deleter, we need to call
    //         compare_exchange_deleter of DataPtr to update deleter
    cpu_storage->data_ptr().unsafe_set_device(c10::Device(at::DeviceType::DPCPP));
```

But there may be other CPU tensors aliasing with this storage, and now you have violated all of their internal invariants. For the `CPU_RAW` shader context, why can't you just use stock CPU tensor representation in this case?

**Comment by jgong5** [comment]
> But there may be other CPU tensors aliasing with this storage, and now you have violated all of their internal invariants.

@ezyang Thanks for the review and questions. The "fallback" and "upgrade" utility functions are only called by IPEX kernels internally. At the boundary of IPEX kernels or at the boundary of where native CPU ops is dispatched, the invariants still hold. We also disallow "inter-op parallelism" to happen for "fallback ops". We haven't put guards to prevent this and should improve the implementation later.

> For the CPU_RAW shader context, why can't you just use stock CPU tensor representation in this case?

Yes, as I replied in https://github.com/pytorch/pytorch/issues/48246#issuecomment-730806285, we should be able to use the stock CPU tensor representation. But we still need the tensor on our own device so that we are able to handle the layout conversion automatically by intercepting the dispatch flow. Handling layout conversion automatically brings better UX than explicit `to_mkldnn` conversions. Our customers found it hard to use the latter since they have to gain additional knowledge on what ops need the conversions and what do not, and they also have to insert `to_mkldnn` and `to_dense` intrusively into the model code.

BTW, we enable the auto-mixed precision by intercepting the device backend dispatch too but we are considering to align the design with the new PyTorch "autocast" mechanism instead.

Welcome to any suggestions. Thanks!

**Comment by ezyang** [comment]
OK, now we're cooking. Some of the discussion is pretty related to my latest comment in #48246. But `to_mkldnn` being hard to use for customers is new information for me and good to try to design for.

If you want to "magically" do layout conversion but still be *fast*, in my experience, eager mode makes life hard. It would be helpful to know what algorithmically IPEX is planning to do, but in my experience, you don't have that many options:

1. You can be so much faster than conventional layout that even if you convert to internal layout for the computation and then convert back to the original layout, this is better than using the normal layout. For example, historically several of cuDNN's convolution kernels were internally in this regime. Based on prior experience with MKLDNN, this is not the case for the kernel and conversion cost dominates.
2. You can offer a well defined contract on when layout is preserved versus not preserved and build out enough support for preserved layout that users can rely on this working. This is what we did for NHWC: it is relatively easy to preserve this layout on simple pointwise operations, and then there are a few operators which are explicitly faster on NHWC. As there is enough coverage for this layout, on more simple model types, it is possible to allocate your parameters in NHWC layout, write normal looking PyTorch code, and mostly get the layout to propagate fairly far in your model. But you need "enough" coverage to make this work, and because PyTorch has a ton of pointwise operations (30% of all our operators), this isn't really feasible without teaching PyTorch about how the layout works (in the case of NHWC, we were lucky, because this could be represented using our preexisting notion of strides). `to_mkldnn()` also falls in this camp, but I guess it was much harder to use because of the coverage problem. I still remember when we originally talked about MKLDNN in https://github.com/pytorch/pytorch/issues/16038 whether or not PyTorch should natively support blocked layout. I understand at the time y'all declined because you wanted to maintain flexibility to change MKLDNN's internal representation, but I just want to emphasize how much you've given up by doing this, and offering that it's never too late to reconsider.
3. You can define some magic, not-well-defined heuristic for when to convert between formats, ala AMP. Because this is eager mode, your heuristic has very little to work with: on any given operation, you have to make the call about whether or not to do the conversion into the other format, without knowing if there are other operations coming in the future that will benefit from this conversion. In the worst case, you degenerate into case (1) and spend a bunch of time thrashing between layout formats. AMP's heuristic is pretty clever and avoid thrash by only being willing to do conversions on parameters, but that obviously also limits the applicability of your memory format (though, who knows: if it's just convolutions you're optimizing, maybe that's good enough).

(2) and (3) differ in how they get exposed to users: (2) is a type based approach, whereas (3) is a mode based approach (you "turn on AMP" and then the semantics of some operators change under this mode). Mode seems to have worked pretty well for AMP, and so if you want magic heuristics for layout too, I probably would suggest implementing these as a mode too. But I don't have all the information here!

**Comment by jgong5** [comment]
@ezyang Thank you so much for the suggestions. The idea of extending `torch.autocast` mechanism to handle auto layout conversion sounds promising to me. It is true that time thrashing might happen in extreme cases, but op-level heuristics is the best we can do in the imperative path. Of course, I'm not sure it would work out all well without a proof-of-concept implementation. Let's sync more details in the upcoming meeting. :-)

**Comment by EikanWang** [comment]
The coming IPEX 1.10 switched the dispatch key and tensor device from XPU to CPU. So the design concern should have gone.
