### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found.

### ISSUE THREAD

**Issue by sifatk69** [intel/intel-extension-for-pytorch#409]
### Describe the issue

I install the module but when i import the the module it shows the error. I check the directory the file is exist.

OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\intel_extension_for_pytorch\bin\intel-ext-pt-gpu.dll" or one of its dependencies.
![sd](https://github.com/intel/intel-extension-for-pytorch/assets/56622065/27c63928-dcfe-4c53-b233-ca7f4dfdcac1)

**Comment by Vipitis** [comment]
you need to activate your oneAPI environment. Inside VSCode there is a really helpful extension that does this for you https://marketplace.visualstudio.com/items?itemName=intel-corporation.oneapi-environment-configurator

**Comment by sifatk69** [comment]
Installed but still showing same error.

**Comment by Vipitis** [comment]
make sure you got conda installed (I believe that is a soft dependency, you don't need to be in any actual conda env). And then run the `Intel OneAPI: setup environment with default variables` command in VSCode. wait for it to finish and show so in the bottom right corner and restart your Jupyer Kernel and Terminals.

**Comment by sifatk69** [comment]
I did it all :(

**Comment by jingxu10** [comment]
@min-jean-cho

**Comment by min-jean-cho** [comment]
Hi @sifatk69, please make sure you had followed these steps.

1. Install Intel oneAPI Base Toolkit
Follow this [link](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=window&distributions=offline) to download and install the latest Windows distribution of oneAPI toolkit.

- **Do not** select **Intel® oneAPI Deep Neural Network Library**.
- Make sure to select **Intel® oneAPI DPC++ Compiler** and **Intel® oneAPI Math Kernel Library**. 

2. **Optional**: Create new conda environment by `conda create -n [env_name] python=[python_version]`

3. Activate oneAPI environment:
`{your_path_to_oneapi}\setvars.bat` e.g. `C:\Program Files (x86)\Intel\oneAPI\setvars.bat`

4. Install Intel® Extension for PyTorch* 
`python -m pip install torch==2.0.0a0 intel_extension_for_pytorch==2.0.110+gitba7f6c1 -f https://developer.intel.com/ipex-whl-stable-xpu`

**Comment by sifatk69** [comment]
@min-jean-cho , I completed everything you write there. I also have the dll file in that location, but I get the same Error.

**Comment by sifatk69** [comment]
Can anyone give me a video link of proper installation?

**Comment by LeonNerd** [comment]
@min-jean-cho ,yeah.I did all the work, but there was still this mistake.Is it related to other envs? Like python.It is on c disk, possibly due to the introduction of this dll, lack of permissions

**Comment by LeonNerd** [comment]
@min-jean-cho yeah.My Graphics card is Iris® Xe Graphics,does it work？
I did all the work, but there was still this mistake.Is it related to other envs? Like python.It is on c disk, possibly due to the introduction of this dll, lack of permissions

**Comment by sifatk69** [comment]
The specified module could not be found. Error loading "C:\Users\Admin\pythonProject\lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies.

**Comment by bouachalazhar** [comment]
> @min-jean-cho yeah.My Graphics card is Iris® Xe Graphics,does it work？ I did all the work, but there was still this mistake.Is it related to other envs? Like python.It is on c disk, possibly due to the introduction of this dll, lack of permissions

Same iGPU, same problem.

**Comment by min-jean-cho** [comment]
cc. @jingxu10 on iGPU support

**Comment by abzb1** [comment]
download latest Microsoft Visual C++ Redistributable and install it

**Comment by necat1** [comment]
> download latest Microsoft Visual C++ Redistributable and install it

Thanks, that worked for me!

**Comment by yinghu5** [comment]
link to #485

**Comment by yinghu5** [comment]
@abzb1 @necat1 , thank you very much for sharing.  

I saw several similar issues during Windows installation in IPEX Git Hub. Like:
https://github.com/intel/intel-extension-for-pytorch/issues/485
https://github.com/intel/intel-extension-for-pytorch/issues/429 [Import intel_extension_for_pytorch fails on windows11

As we analyzed, the main root cause may still be in the installation environment, please note:

Neither “windows powershell” or “anaconda powershell prompt” does not work, if using conda prompt, we need to use "anaconda prompt".
please use the anaconda prompt itself, not in PS (powershell) environment. https://github.com/intel/intel-extension-for-pytorch/issues/485

Install step missing like missing install oneAPI or missing activate oneAPI, or missing other package:
conda install pkg-config libuv etc.

Other dependencies missing, like MSVC redistribution files.
so in summary, please create a new conda environment and
follow the install guide: https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.30%2bxpu&os=windows&package=pip

Pre-requisites installation in order :
3.1) GPU driver
3.2) MSVC environment or Install Microsoft Visual C++ Redistributable
Install Microsoft Visual C++ Redistributable from [Microsoft website](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022).
3.3) Install oneAPI: 2024.1 {as no download link is available for 2023.2 anymore}
(https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html)
3.4) open Python environment, like miconda3(latest) Python: 3.10

In anaconda prompt (please notes some VS code, call power shell by default)

3.5) Steps to reproduce:
conda create --name llmenv python=3.10
conda activate llm
call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat" -> DPCPPROOT
call "C:\Program Files (x86)\Intel\oneAPI\compiler\mkl\env\vars.bat" -> MKLROOT

conda install pkg-config libuv
python -m pip install torch==2.1.0.post2 torchvision==0.16.0.post2 torchaudio==2.1.0.post2 intel-extension-for-pytorch==2.1.30 --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/
Sanity test:
python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.version); print(ipex.version); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"

If you followed those and still run into the problem, please let us know the installation steps you are using. and collect your envs by this [collect_env.py](https://github.com/intel/intel-extension-for-pytorch/blob/main/scripts/collect_env.py)

Thanks
