### ISSUE TITLE
Import intel_extension_for_pytorch fails on windows11

### ISSUE THREAD

**Issue by rairatne** [intel/intel-extension-for-pytorch#473]
### Describe the bug

HW used: ADL i7 (12700H)/ARC770

OS Name	Microsoft Windows 11 Pro: Version	10.0.22621 Build 22621
ARC Driver: 31.0.101.4972 /  31.0.101.4953 {Tried with both drivers}

Pre-requisites:
miconda3(latest)
Python: 3.9
oneAPI: 2024.0 {as no download link available for 2023.2 anymore}

Steps to reproduce:
conda create --name llmenv python=3.9
conda activate llm
call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat" -> DPCPPROOT 
call "C:\Program Files (x86)\Intel\oneAPI\compiler\mkl\env\vars.bat" -> MKLROOT

conda install pkg-config libuv
python -m pip install torch==2.0.0a0 intel-extension-for-pytorch==2.0.110+gitba7f6c1 --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/

#sanity test
python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"

This throws Error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\intel\miniconda3\envs\llm\lib\site-packages\intel_extension_for_pytorch\__init__.py", line 89, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\intel\miniconda3\envs\llm\lib\site-packages\intel_extension_for_pytorch\bin\intel-ext-pt-gpu.dll" or one of its dependencies.
![image](https://github.com/intel/intel-extension-for-pytorch/assets/81367619/0fd89c72-3c69-459c-bb37-8156006fe8b2)

### Versions

PyTorch version: 2.0.0a0+gitc6a572f
PyTorch CXX11 ABI: No
IPEX version: N/A
IPEX commit: N/A
Build type: N/A

OS: Microsoft Windows 11 Pro
GCC version: N/A
Clang version: 16.0.5
IGC version: 2024.0.0 (2024.0.0.20231017)
CMake version: version 3.27.7
Libc version: N/A

Python version: 3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is XPU available: N/A
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration:
N/A
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture=9
CurrentClockSpeed=2300
DeviceID=CPU0
Family=198
L2CacheSize=11776
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2300
Name=12th Gen Intel(R) Core(TM) i7-12700H
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.0.110+gitba7f6c1
[pip3] numpy==1.26.2
[pip3] torch==2.0.0a0+gitc6a572f
[conda] intel-extension-for-pytorch 2.0.110+gitba7f6c1          pypi_0    pypi
[conda] mkl-include               2024.0.0                 pypi_0    pypi
[conda] mkl-static                2024.0.0                 pypi_0    pypi
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] torch                     2.0.0a0+gitc6a572f          pypi_0    pypi

**Comment by rairatne** [comment]
Is this a root cause #449 ? when are we planning to host a new python whl for ipex on Windows based on latest one API and GPU driver?

**Comment by JeroenAdam** [comment]
I'm also waiting for this.

**Comment by hanikhatib** [comment]
Also waiting for this (Windows 10). It would be of great benefit to the open source community as a whole

**Comment by jingxu10** [comment]
@min-jean-cho @ashokei

**Comment by kred** [comment]
Intel, this is shame. Just bought ARC A770 and wanted to play with PyTorch. oneAPI 2024 breaks your official PyTorch package. I can live with that, but for whatever insane reason, official way to download older oneAPI package is to pay for support. Are you kidding?

So, current (as of today) Intel's PyTorch build 2.0.0a work with oneAPI 2023.2 only. Link to download that installer you may still find in oneAPI official repository: https://github.com/oneapi-src/oneapi-ci/commit/cf8ed233e0c32b0f31ed09bc587b281e99e1df12#diff-407ded4161c16de89574d5450eea4c1e6d89390b0363974918115723f093a735

For torchvision - download 0.15.1 wheel from PyPI, modify manually manifest (this is actually zip file) to be dependent on torch-2.0.0a instead of 2.0.0.

Your welcome, Intel.

**Comment by ebeshero** [comment]
Maybe hopeful? This intel extension was just released for torch 2.2.0
https://github.com/intel/intel-extension-for-pytorch/releases

**Comment by kred** [comment]
> Maybe hopeful? This intel extension was just released for torch 2.2.0 https://github.com/intel/intel-extension-for-pytorch/releases

@ebeshero It was released for CPU so far.

**Comment by ebeshero** [comment]
Yeah, I was sad it was missing xpu. And I am having endless trouble installing the old one properly.

**Comment by ccomee** [comment]
Anything new from this ? I have the same issue and haven't been able to find a solution...

**Comment by ZailiWang** [comment]
Also, please use "developer command prompt for vs 2022" or "anaconda prompt", instead of "powershell prompt".

**Comment by yinghu5** [comment]
Hi @ccomee ,

For your reference: 

If I follow the original steps of [rairatne]

Pre-requisites:
miconda3(latest)
Python: 3.9
oneAPI: 2024.0 {as no download link available for 2023.2 anymore}

Steps to reproduce:
conda create --name llmenv python=3.9
conda activate llm
call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat" -> DPCPPROOT
call "C:\Program Files (x86)\Intel\oneAPI\compiler\mkl\env\vars.bat" -> MKLROOT

conda install pkg-config libuv
python -m pip install torch==2.0.0a0 intel-extension-for-pytorch==2.0.110+gitba7f6c1 --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/

#sanity test
python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.version); print(ipex.version); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"

I able to reproduce the original problem. 

But in the same conda environment,   if I follow the steps in official doc:  https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.10%2Bxpu. 

python -m pip install torch==2.1.0a0 torchvision==0.16.0a0 torchaudio==2.1.0a0 intel-extension-for-pytorch==2.1.10 --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/

then everything is fine. So, I guess the original problem is caused by missing torchvision and audio dependency dll. 

could you please try the install command again and let us know if it works? 
   
   supposed you have oneAPI 2024.0 installed, MSVC 2022, or MSVC runtime dll installed. 
   open one anaconda prompt  (instead of PowerShell prompt or other developer command prompt for vs 2022) 
  
  conda create --name llmenv python=3.9
  conda activate llm
  call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat" 
  call "C:\Program Files (x86)\Intel\oneAPI\compiler\mkl\env\vars.bat" 

   conda install pkg-config libuv
   **python -m pip install torch==2.1.0a0 torchvision==0.16.0a0 torchaudio==2.1.0a0 intel-extension-for-pytorch==2.1.10 --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/**
   
   python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.version); print(ipex.version); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"
   
   The output is like 
<module 'torch.version' from 'C:\\ProgramData\\miniconda3\\envs\\ipex_huiyan\\lib\\site-packages\\torch\\version.py'>
<function version at 0x000001B15174BAF0>
[0]: _DeviceProperties(name='Intel(R) Arc(TM) Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=7133MB, max_compute_units=112, gpu_eu_count=112)

**Comment by ccomee** [comment]
Hello @yinghu5 ; 

Thank you for this response. I have been trying to make this work for weeks and couldn't figure it out. I tried the step you gave but I still had the same issue. I ended up creating another environment and redoing the whole process, and now it worked ! 

I don't know what I did wrong for the first environment but now everything is in order

**Comment by SoldierWz** [comment]
So the final solution is to re-install the steps in a new environment? But I tried it and still got the same problem.

**Comment by SoldierWz** [comment]
There is also a question about the test command in the official tutorial：
call {DPCPPROOT}\env\vars.bat
call {MKLROOT}\env\vars.bat
I tried but the output：System can not find the route.

**Comment by SoldierWz** [comment]
Sorry, I may not be using Intel graphics cards for work in the near future. If I still encounter such a problem when I use it again, I will restart with a new problem. grateful.







 王震
***@***.***











Original:
From：feng-intel ***@***.***>Date：2024-04-15 14:51:48(中国 (GMT+08:00))To：intel/intel-extension-for-pytorch ***@***.***>Cc：SoldierWz ***@***.***> , Mention ***@***.***>Subject：Re: [intel/intel-extension-for-pytorch] Import intel_extension_for_pytorch fails on windows11 (Issue #473)
@SoldierWz
 Could you start a new issue? And give more details about steps, env, and the problem? Thanks.
This issue is closed.

**Comment by yinghu5** [comment]
Dear all, 

I saw several similar issues during windows installation in IPEX Git Hub.  Like: 
#485 [OSError: [WinError 126] The specified module could not be found. Error loading "C:\path\to\venv\lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies · Issue #485 · intel/intel-extension-for-pytorch (github.com)](https://github.com/intel/intel-extension-for-pytorch/issues/485)
#429 [Import intel_extension_for_pytorch fails on windows11 

As we analyzed, the main root cause may still be in the installation environment, please note: 

1)	Neither “windows powershell” or “anaconda powershell prompt” does not work, if using conda prompt, we need to use "anaconda prompt".
please use the anaconda prompt itself, not in PS (powershell) environment.  [OSError: [WinError 126] The specified module could not be found. Error loading "C:\path\to\venv\lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies · Issue #485 · intel/intel-extension-for-pytorch (github.com)](https://github.com/intel/intel-extension-for-pytorch/issues/485)

2)	Install step missing like missing install oneAPI or missing activate oneAPI,  or missing other package:  
 **conda install pkg-config libuv etc.** 

3)	Other dependencies missing, like MSVC redistribution files.

so in summary, , please create a new conda environment  and 
 follow the install guide:  https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.30%2bxpu&os=windows&package=pip

Pre-requisites installation in order : 
3.1) GPU driver
3.2) MSVC environment or Install Microsoft Visual C++ Redistributable
Install Microsoft Visual C++ Redistributable from [Microsoft website](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022).
3.3)  Install oneAPI: 2024.1 {as no download link is available for 2023.2 anymore}

3.4) open Python environment, like miconda3(latest) Python: 3.10

In  anaconda prompt  (please notes some MSVS code, call power shell by default)

3.5) Steps to reproduce:
conda create --name llmenv python=3.10
conda activate llm
call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat" -> DPCPPROOT
call "C:\Program Files (x86)\Intel\oneAPI\compiler\mkl\env\vars.bat" -> MKLROOT

conda install pkg-config libuv
  python -m pip install torch==2.1.0.post2 torchvision==0.16.0.post2 torchaudio==2.1.0.post2 intel-extension-for-pytorch==2.1.30 --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/
 Sanity test: 
  python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"
  
 If you followed those and  still run into the problem, please let us know the installation steps you are using.  and  collect your envs by this [collect_env.py](https://github.com/intel/intel-extension-for-pytorch/blob/main/scripts/collect_env.py)

Thanks

**Comment by yinghu5** [comment]
please feel free to reopen if any new issues

**Comment by StEvUgnIn** [comment]
I have been having a hard time configuring oneDNN for PyTorch for days. It was much easier to configure with tensorflow.

https://gist.github.com/StEvUgnIn/ee0e34e34ae27cd709050d5b6483f819
