### ISSUE TITLE
matmul does not support broadcast.

### ISSUE THREAD

**Issue by EikanWang** [intel/intel-extension-for-pytorch#9]
The unit test case of test_torch.py failed because matmul does not support broadcast.

Unit test case:
=======================================
FAIL: test_broadcast_batched_matmul_dpcpp (__main__.TestTorchDeviceTypeDPCPP)

**Comment by EikanWang** [comment]
@pinzhenx , could we capture the case if the input tensor needs to be broadcasted, and then prompt a message?

**Comment by pinzhenx** [comment]
Though we do not support broadcast right now, the issue in this test case is caused by https://github.com/intel/intel-extension-for-pytorch/issues/50

In a call to `mm_out`, the input sizes were `[24, 2]` and `[2, 1]`, the size of `out` was `[3, 8]`, which should be rewritten by mm with new out shape `[24, 1]`
